using Hamon.Layout;
using Hamon.Testing.Regression;
using Hamon.Widgets;
using Xunit;

namespace Hamon.Tests.Rendering;

/// <summary>
/// Image regression for a single component (real pixels + real font golden).
/// Detects GUI drawing corruption (layout/color/rounded corners/clips/overlaps/fonts). <c>HAMON_UPDATE_GOLDENS=1</c>Generated by.
/// </summary>
public class WidgetImageRegressionTests
{
    private const string Cat = "unit";
    private static readonly Color Accent = new(80, 130, 220);

    private static void Settle(HamonRoot h, int w, int ht)
    {
        for (int i = 0; i < 24; i++)
        {
            h.Update(new Size(w, ht), 0.1f);
        }
    }

    // ---- ボタン状態 ----

    private static Widget ButtonScene() => new Align
    {
        Alignment = Alignment.Center,
        Child = new Button
        {
            Node = new FocusNode(),
            OnPressed = () => { },
            Background = new Color(48, 52, 64),
            Radius = 10f,
            Padding = EdgeInsets.Symmetric(20f, 12f),
            Child = new Text("Button") { FontSize = 18f },
        },
    };

    [Fact]
    public void Button_Idle() => GoldenImage.AssertRender(180, 80, ButtonScene, Cat, "button-idle");

    [Fact]
    public void Button_Hovered() => GoldenImage.AssertRender(180, 80, ButtonScene, Cat, "button-hover",
        drive: h => { h.DispatchHover(new Vec2(90, 40)); Settle(h, 180, 80); });

    [Fact]
    public void Button_Pressed() => GoldenImage.AssertRender(180, 80, ButtonScene, Cat, "button-pressed",
        drive: h => { h.DispatchPointer(new PointerEvent(new Vec2(90, 40), PointerPhase.Down, 0f)); Settle(h, 180, 80); });

    // ---- トグル/入力系 ----

    [Fact]
    public void Checkbox_BothStates() => GoldenImage.AssertRender(140, 70, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new Row
        {
            Children = new Widget[]
            {
                new Checkbox { Value = true, OnChanged = _ => { } },
                new SizedBox { Width = Dimension.Px(20) },
                new Checkbox { Value = false, OnChanged = _ => { } },
            },
        },
    }, Cat, "checkbox");

    [Fact]
    public void Switch_BothStates() => GoldenImage.AssertRender(160, 70, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new Row
        {
            Children = new Widget[]
            {
                new Switch { Value = true, OnChanged = _ => { } },
                new SizedBox { Width = Dimension.Px(20) },
                new Switch { Value = false, OnChanged = _ => { } },
            },
        },
    }, Cat, "switch");

    [Fact]
    public void Radio_Selected() => GoldenImage.AssertRender(140, 70, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new Row
        {
            Children = new Widget[]
            {
                new Radio<int> { Value = 1, GroupValue = 1, OnChanged = _ => { } },
                new SizedBox { Width = Dimension.Px(20) },
                new Radio<int> { Value = 2, GroupValue = 1, OnChanged = _ => { } },
            },
        },
    }, Cat, "radio");

    [Fact]
    public void Slider_Half() => GoldenImage.AssertRender(240, 60, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new SizedBox { Width = Dimension.Px(200), Child = new Slider { Value = 0.4f, OnChanged = _ => { } } },
    }, Cat, "slider");

    [Fact]
    public void TextField_Placeholder() => GoldenImage.AssertRender(240, 64, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new SizedBox { Width = Dimension.Px(200), Child = new TextField { Controller = new TextEditingController(), Node = new FocusNode(), Placeholder = "Search" } },
    }, Cat, "textfield-placeholder");

    [Fact]
    public void TextField_Text() => GoldenImage.AssertRender(240, 64, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new SizedBox { Width = Dimension.Px(200), Child = new TextField { Controller = new TextEditingController("Hello"), Node = new FocusNode(), Placeholder = "Search" } },
    }, Cat, "textfield-text");

    [Fact]
    public void Dropdown_Closed() => GoldenImage.AssertRender(200, 64, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new Dropdown<int>
        {
            Value = 1,
            OnChanged = _ => { },
            Items = new[]
            {
                new DropdownItem<int>(1, new Text("One") { FontSize = 14f }),
                new DropdownItem<int>(2, new Text("Two") { FontSize = 14f }),
            },
        },
    }, Cat, "dropdown");

    // ---- プログレス（過去バグ：スピナー継ぎ目） ----

    [Fact]
    public void ProgressBar_Linear() => GoldenImage.AssertRender(240, 48, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new ProgressBar { Value = 0.6f, Width = Dimension.Px(200), Height = 10f, Fill = Accent },
    }, Cat, "progressbar");

    [Fact]
    public void CircularProgress_Determinate_Ring() => GoldenImage.AssertRender(96, 96, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new CircularProgressIndicator { Value = 0.66f, Diameter = 72f, StrokeWidth = 8f, BackgroundColor = new Color(70, 74, 90), Color = Accent },
    }, Cat, "radial-progress");

    [Fact]
    public void Spinner_Indeterminate() => GoldenImage.AssertRender(80, 80, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new CircularProgressIndicator { Diameter = 48f, StrokeWidth = 5f, Color = Accent },
    }, Cat, "spinner");

    // ---- テキスト/コンテナ/カード/レイアウト ----

    [Fact]
    public void Text_Styles() => GoldenImage.AssertRender(260, 140, () => new Align
    {
        Alignment = Alignment.TopLeft,
        Child = new Column
        {
            Children = new Widget[]
            {
                new Text("Heading 24") { FontSize = 24f },
                new Text("Body 16 colored") { FontSize = 16f, Color = Accent },
                new Text("Small 12 muted") { FontSize = 12f, Color = new Color(150, 150, 160) },
            },
        },
    }, Cat, "text-styles");

    [Fact]
    public void Container_Rounded() => GoldenImage.AssertRender(140, 100, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new Container { Width = Dimension.Px(100), Height = Dimension.Px(64), Radius = 16f, Color = new Color(60, 130, 110) },
    }, Cat, "container-rounded");

    [Fact]
    public void Card_Elevated() => GoldenImage.AssertRender(200, 120, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new Material
        {
            Color = new Color(54, 58, 72),
            Radius = 12f,
            Elevation = 4f,
            Child = new Container { Padding = EdgeInsets.All(16f), Child = new Text("Card") { FontSize = 18f } },
        },
    }, Cat, "card-elevated");

    [Fact]
    public void Gradient_Fill() => GoldenImage.AssertRender(160, 100, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new Material
        {
            Color = new Color(40, 80, 160),
            GradientTo = new Color(150, 60, 120),
            Radius = 10f,
            Child = new SizedBox { Width = Dimension.Px(120), Height = Dimension.Px(64) },
        },
    }, Cat, "gradient");

    [Fact]
    public void Opacity_Half() => GoldenImage.AssertRender(140, 100, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new Opacity { Value = 0.5f, Child = new Container { Width = Dimension.Px(100), Height = Dimension.Px(64), Radius = 8f, Color = Accent } },
    }, Cat, "opacity");

    [Fact]
    public void Transform_Scaled() => GoldenImage.AssertRender(140, 120, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new Transform { Scale = 1.4f, Child = new Container { Width = Dimension.Px(64), Height = Dimension.Px(48), Radius = 8f, Color = new Color(180, 120, 60) } },
    }, Cat, "transform-scale");

    [Fact]
    public void Toast_Pill() => GoldenImage.AssertRender(260, 90, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new Material
        {
            Color = new Color(60, 64, 78),
            Radius = 20f,
            Elevation = 3f,
            Child = new Container { Padding = EdgeInsets.Symmetric(20f, 10f), Child = new Text("Saved") { FontSize = 14f } },
        },
    }, Cat, "toast-pill");

    [Fact]
    public void Layout_RowColumn() => GoldenImage.AssertRender(220, 120, () => new Align
    {
        Alignment = Alignment.Center,
        Child = new Column
        {
            Children = new Widget[]
            {
                new Row
                {
                    Children = new Widget[]
                    {
                        new Container { Width = Dimension.Px(40), Height = Dimension.Px(40), Color = new Color(200, 80, 80) },
                        new SizedBox { Width = Dimension.Px(8) },
                        new Container { Width = Dimension.Px(40), Height = Dimension.Px(40), Color = new Color(80, 200, 80) },
                        new SizedBox { Width = Dimension.Px(8) },
                        new Container { Width = Dimension.Px(40), Height = Dimension.Px(40), Color = new Color(80, 80, 200) },
                    },
                },
                new SizedBox { Height = Dimension.Px(8) },
                new Container { Width = Dimension.Px(136), Height = Dimension.Px(24), Radius = 6f, Color = new Color(90, 90, 100) },
            },
        },
    }, Cat, "layout-row-column");
}
