using Hamon.Layout;
using Hamon.Testing.Perf;
using Hamon.Testing.Regression;
using Hamon.Widgets;
using Xunit;

namespace Hamon.E2E.Tests;

/// <summary>
/// Image regression for integration (full screen compositing).
/// (layout/overlap/scroll/overlay z-order/tab switching/drag display/toast) is detected.
/// golden is<c>HAMON_UPDATE_GOLDENS=1</c>Generated by.
/// </summary>
public class IntegrationImageRegressionTests
{
    private const string Cat = "e2e";
    private const int W = 360;
    private const int H = 720;

    private static void Settle(HamonRoot h, int w, int ht, int frames = 24)
    {
        for (int i = 0; i < frames; i++)
        {
            h.Update(new Size(w, ht), 0.05f);
        }
    }

    [Fact]
    public void Dashboard_Initial() => GoldenImage.AssertRender(W, H, Screens.Dashboard, Cat, "dashboard");

    [Fact]
    public void Settings_Initial() => GoldenImage.AssertRender(W, H, Screens.Settings, Cat, "settings");

    [Fact]
    public void List_Initial() => GoldenImage.AssertRender(W, H, () => Screens.VirtualList(1000), Cat, "list");

    [Fact]
    public void List_Scrolled()
    {
        var ctrl = new ScrollController();
        GoldenImage.AssertRender(W, H, () => Screens.VirtualList(1000, ctrl), Cat, "list-scrolled",
            drive: h =>
            {
                for (int f = 0; f < 14; f++)
                {
                    InputScript.DragScroll(new Vec2(180, 360), 30f, startFrame: 0, frames: 12)(h, f);
                    h.Update(new Size(W, H), 0.016f);
                }

                Settle(h, W, H);
                Assert.True(ctrl.Offset > 80f, $"スクロールしていない (offset={ctrl.Offset})");
            });
    }

    [Fact]
    public void Inventory_Initial() => GoldenImage.AssertRender(W, 480, Screens.Inventory, Cat, "inventory");

    [Fact]
    public void Inventory_Dragging() => GoldenImage.AssertRender(W, 480, Screens.Inventory, Cat, "inventory-dragging",
        drive: h =>
        {
            h.DispatchPointer(new PointerEvent(new Vec2(48, 92), PointerPhase.Down, 0f));
            h.DispatchPointer(new PointerEvent(new Vec2(180, 300), PointerPhase.Move, 0.02f)); // ドラッグ開始＝フィードバックが追従
            Settle(h, W, 480, 6);
            // 離さずにドラッグ中のフレームを撮る。
        });

    [Fact]
    public void Tabs_First()
    {
        TabController? ctrl = null;
        GoldenImage.AssertRender(W, 360, () => { ctrl ??= new TabController(2); return Screens.TabsScreen(ctrl); }, Cat, "tabs-first");
    }

    [Fact]
    public void Tabs_Second()
    {
        TabController? ctrl = null;
        GoldenImage.AssertRender(W, 360, () => { ctrl ??= new TabController(2); return Screens.TabsScreen(ctrl); }, Cat, "tabs-second",
            drive: h => { ctrl!.Select(1); Settle(h, W, 360); });
    }

    [Fact]
    public void Form_Initial() => GoldenImage.AssertRender(W, 560, () => new Container
    {
        Color = new Color(30, 32, 40),
        Padding = EdgeInsets.All(16f),
        Child = new Column
        {
            Children = new Widget[]
            {
                new Text("Sign up") { FontSize = 22f, Color = new Color(230, 232, 240) },
                new SizedBox { Height = Dimension.Px(16) },
                new TextField { Controller = new TextEditingController("Ada Lovelace"), Node = new FocusNode(), Placeholder = "Name" },
                new SizedBox { Height = Dimension.Px(12) },
                new TextField { Controller = new TextEditingController(), Node = new FocusNode(), Placeholder = "Email" },
                new SizedBox { Height = Dimension.Px(16) },
                new Row
                {
                    CrossAxisAlignment = CrossAxisAlignment.Center,
                    Children = new Widget[]
                    {
                        new Text("Subscribe") { FontSize = 15f, Color = new Color(230, 232, 240) },
                        new Spacer(),
                        new Switch { Value = true, OnChanged = _ => { } },
                    },
                },
                new SizedBox { Height = Dimension.Px(16) },
                new Button { OnPressed = () => { }, Background = new Color(80, 130, 220), Radius = 10f, Padding = EdgeInsets.Symmetric(20f, 12f), Child = new Text("Create account") { FontSize = 16f } },
            },
        },
    }, Cat, "form");

    [Fact]
    public void BottomSheet_Open() => GoldenImage.AssertRender(W, H, Screens.Dashboard, Cat, "bottom-sheet",
        drive: h => { Screens.ShowSheet(h); Settle(h, W, H); });

    [Fact]
    public void Toast_Shown() => GoldenImage.AssertRender(W, H, Screens.Dashboard, Cat, "toast",
        drive: h => { h.ShowSnackbar("Saved successfully", 5f); Settle(h, W, H); });
}
